version: '3.4'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: e99rntuUXMGHB6Zt
    volumes:
      - mysql:/var/lib/mysql

networks:
  default:
    external:
      name: databases

volumes:
  mysql:
    external: true

