version: '3.4'

services:

  adminer:
    image: adminer:4.6.2-standalone
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

networks:
  default:
    external:
      name: databases

