version: '3.4'

services:

  postgres:
    image: postgres:9.6.5
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 5aJhjS7g7SAzE56K
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  default:
    external:
      name: databases

volumes:
  postgres:
    external: true

